apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo-app-ext
  labels:
    app: prometheus-demo-app-ext
spec:
  type: LoadBalancer
  selector:
    app: prometheus-demo-app
  ports:
  - port: 8080
    targetPort: 8000
    name: web
